### ISSUE TITLE
Актуализировать основную ветку

### ISSUE THREAD

**Issue by kolobai** [AlistairGray/test-work#7]
Слить все ветки в основную ветку и удалить неиспользуемые. При слиянии могут возникнуть конфликты, которые необходимо разрешить.

**Comment by AlistairGray** [comment]
Слил все ветки в master. Удалил не используемые. При слиянии проблем не возникло, т.к. ветвление делал правильно (просто забывал выталкивать ветку master в удалённый репозиторий)
